config/routes.rb
Rails.application.routes.draw do
  get 'uploader/image'
  devise_for :users
  resources :sections
  resources :reviews
  resources :contacts
  resources :categories
  resources :policies
  resources :coachings, path: 'coaching'
  root 'home#index'

  namespace :admin do
    root to: 'dashboard#index'

    resources :blogs
    resources :resources
    resources :sections
    resources :users
    resources :reviews
    resources :categories
    resources :policies
    resources :coaching
  end

  resources :reorder do
    patch :move
  end

  post 'reorder/update_sections_order', to: 'reorder#update_sections_order'

  post 'uploader/image' => 'uploader#image'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'errors/not_found'
  get 'errors/internal_server_error'

  get '/contact_us', to: 'contact_us#new'
  post '/contact_us', to: 'contact_us#create'
  get 'contact_us/sent'
  get 'contact_us/error'

  resources :blogs, path: :blog

  resources :resources

  require 'active_storage/engine'
  ActiveStorage::Engine.routes.draw do
    get '/rails/active_storage/blobs/redirect/:signed_id/*filename' => 'active_storage/blobs#show',
        as: :rails_service_blob
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # test for deployment

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :blog_categories, dependent: :destroy
  has_many :categories, through: :blog_categories
  has_one_attached :preview

  accepts_nested_attributes_for :blog_categories, allow_destroy: true
end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/blogs_category.rb
class BlogsCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blog_categories
  has_many :blogs, through: :blog_categories
  validates :name, uniqueness: true
end

app/models/coaching.rb
class Coaching < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/contact_us.rb
# frozen_string_literal: true
class ContactUs < MailForm::Base
  attribute :name
  attribute :nickname
  attribute :subject
  attribute :email
  attribute :email_confirmation
  attribute :message

  validates :name, :subject,
            presence: true,
            allow_blank: false,
            format: { with: /\A[a-zA-Z\s-]+\z/, message: 'Only allows letters, spaces, and hyphens' }

  validates :email,
            presence: true, format: { with: URI::MailTo::EMAIL_REGEXP },
            allow_blank: false,
            length: {
              minimum: 5,
              maximum: 50
            }

  validates :email_confirmation,
            presence: true

  validate :emails_match

  validates :message,
            allow_blank: false,
            length: {
              minimum: 10,
              maximum: 500
            }

  def headers
    {
      to: 'stuart@scbexecutivecoaching.com', # change this to be the email you want sent to
      subject: 'SCB Executive Coaching Query',
      from: 'stuart@scbexecutivecoaching.com',  # change this to be the email it is coming from
      reply_to: %("#{name}" <#{email}>)
    }
  end

  def emails_match
    if email != email_confirmation
      errors.add(:email_confirmation, "doesn't match Email")
    end
  end
end

app/models/policy.rb
class Policy < ApplicationRecord
end

app/models/reorder.rb
class Reorder < ApplicationRecord
  validates :position, presence: true
  validates :position, numericality: { only_integer: true, greater_than: 0 }
  #has_many :sections, -> { order(position: :asc) }, dependent: :destroy

  private
  def set_default_position
    # Defaults to the next highest position
    self.position = (Section.maximum(:position) || 0) + 1
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_many :resource_categories, dependent: :destroy
  has_many :categories, through: :resource_categories
  has_one_attached :preview
  has_one_attached :file_upload
  before_save :purge_old_file, if: :file_upload_changed?

  accepts_nested_attributes_for :resource_categories, allow_destroy: true

  private

  def purge_old_file
    file_upload.purge_later if file_upload.attached?
  end
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord

  validates :body, presence: false
  validates :name, presence: true
  validates :background_colour, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @reviews = Review.all
    @home_sections = Section.order(:order).where(show_on_home: true)
    @menu_sections = Section.order(:order)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/views/home/_reviews.html.erb
<!-- app/views/home/_reviews.html.erb -->
<% if @reviews.blank? %>
  <%= link_to 'Create Review', new_review_path %>
<% else %>
  <div data-controller="carousel" style="height:260px; width: 100%; overflow:hidden" class="my-5 flex justify-between align-center">
	<button data-action="click->carousel#previousSlide">
	  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-scb-white">
		<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
	  </svg>
	</button>

	<% @reviews.each do |review| %>
	  <div class="slide absolute w-2/3 inset-x-0 my-auto mx-auto bg-scb-blue" data-carousel-target="slide">
		<div class="h-64 grid place-items-center max-w-7xl text-center mx-auto">
		  <h2 class="mb-5 mx-auto  font-poppins"><%= review.body&.html_safe %></h2>
		  <p class="text-scb-white"><%= review.author %></p>
		</div>
		<div class="flex gap-3 mx-auto justify-center">
		  <% if user_signed_in? %>
			<%= link_to 'Create Review', new_review_path, class: "bg-scb-gray text-scb-black rounded-lg p-3" %>
			<%= link_to 'Edit Review', edit_review_path(review.id), class: "bg-scb-white text-scb-black rounded-lg p-3" %>
			<%= link_to "Delete Review", review_path(review), "data-turbo-method": :delete, "data-turbo-confirm": "Are you sure?", class: "bg-red-700 rounded-lg p-3 text-scb-white" %>
		  <% end %>
		</div>
	  </div>
	<% end %>

	<button data-action="click->carousel#nextSlide">
	  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-scb-white">
		<path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
	  </svg>
	</button>
  </div>
<% end %>

app/views/home/_sections.html.erb
<% if user_signed_in? %>
  <div class="p-6 max-w-7xl mx-auto">
    <%= link_to 'Create Section', new_section_path, class: "bg-scb-gray text-scb-black rounded-lg p-3 m-3 ml-0 button" %>
</div>
<% end %>

<% sections.each do |section| %>
  <% button_bg_class = button_class_for_background(section.background_colour) %>
  <% button_text_class = button_class_for_text(button_bg_class) %>

  <section data-scroll-target="<%= section.name.downcase %>" id="<%= section.name.downcase %>" class="mx-auto bg-<%= section.background_colour %> py-16">
    <div class="mx-auto p-3">
      <div class="mx-auto flex flex-col items-center justify-center py-16 text-center max-w-7xl">
        <% unless section.hide_title %>
          <h1 class="text-<%= section.title_colour %> <%= section.title_size %> font-bold mb-5 font-poppins font-bold tracking-normal"><%= section.title %></h1>
        <% end %>

        <% if section.reviews %>
          <%= render 'reviews', locals: "reviews: @reviews"%>
        <% end %>

        <% unless section.reviews %>
          <h2 class="text-<%= section.body_text_colour %> <%= section.body_text_size %> text-<%= section.link_colour %> <%= section.alignment %> font-poppins px-6"><%= section.body&.html_safe %></h2>
        <% end %>
      </div>

      <div class="flex gap-3 mx-auto max-w-7xl px-6">
        <% if user_signed_in? %>
        <%= link_to 'Edit Section', edit_section_path(section), class: "#{button_bg_class} #{button_text_class} rounded-lg p-3 no-underline button" %>
        <%= link_to "Delete Section", section_path(section), "data-turbo-method": :delete, "data-turbo-confirm": "Are you sure?", class: "bg-red-700 rounded-lg p-3 text-scb-white button" %>
          <% end %>
      </div>

      </div>
  </section>
<% end %>

app/views/home/index.html.erb
<% content_for :meta_title, "SCB Executive Life Coaching" %>
<% content_for :meta_description, "SCB Executive Coaching" %>

<div>
	<div id="sections_list">
    	<%= render partial: 'home/sections', locals: { sections: @home_sections } %>
	</div>
</div>