config/routes.rb
Rails.application.routes.draw do
  get 'uploader/image'
  devise_for :users
  resources :sections
  resources :reviews
  resources :contacts
  resources :categories
  resources :policies
  resources :coachings, path: 'coaching'
  root 'home#index'

  namespace :admin do
    root to: 'dashboard#index'

    resources :blogs
    resources :resources
    resources :sections
    resources :users
    resources :reviews
    resources :categories
    resources :policies
    resources :coaching
  end

  resources :reorder do
    patch :move
  end

  post 'reorder/update_sections_order', to: 'reorder#update_sections_order'

  post 'uploader/image' => 'uploader#image'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'errors/not_found'
  get 'errors/internal_server_error'

  get '/contact_us', to: 'contact_us#new'
  post '/contact_us', to: 'contact_us#create'
  get 'contact_us/sent'
  get 'contact_us/error'

  resources :blogs, path: :blog

  resources :resources

  require 'active_storage/engine'
  ActiveStorage::Engine.routes.draw do
    get '/rails/active_storage/blobs/redirect/:signed_id/*filename' => 'active_storage/blobs#show',
        as: :rails_service_blob
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # test for deployment

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :blog_categories, dependent: :destroy
  has_many :categories, through: :blog_categories
  has_one_attached :preview

  accepts_nested_attributes_for :blog_categories, allow_destroy: true
end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/blogs_category.rb
class BlogsCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blog_categories
  has_many :blogs, through: :blog_categories
  validates :name, uniqueness: true
end

app/models/coaching.rb
class Coaching < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/contact_us.rb
# frozen_string_literal: true
class ContactUs < MailForm::Base
  attribute :name
  attribute :nickname
  attribute :subject
  attribute :email
  attribute :email_confirmation
  attribute :message

  validates :name, :subject,
            presence: true,
            allow_blank: false,
            format: { with: /\A[a-zA-Z\s-]+\z/, message: 'Only allows letters, spaces, and hyphens' }

  validates :email,
            presence: true, format: { with: URI::MailTo::EMAIL_REGEXP },
            allow_blank: false,
            length: {
              minimum: 5,
              maximum: 50
            }

  validates :email_confirmation,
            presence: true

  validate :emails_match

  validates :message,
            allow_blank: false,
            length: {
              minimum: 10,
              maximum: 500
            }

  def headers
    {
      to: 'stuart@scbexecutivecoaching.com', # change this to be the email you want sent to
      subject: 'SCB Executive Coaching Query',
      from: 'stuart@scbexecutivecoaching.com',  # change this to be the email it is coming from
      reply_to: %("#{name}" <#{email}>)
    }
  end

  def emails_match
    if email != email_confirmation
      errors.add(:email_confirmation, "doesn't match Email")
    end
  end
end

app/models/policy.rb
class Policy < ApplicationRecord
end

app/models/reorder.rb
class Reorder < ApplicationRecord
  validates :position, presence: true
  validates :position, numericality: { only_integer: true, greater_than: 0 }
  #has_many :sections, -> { order(position: :asc) }, dependent: :destroy

  private
  def set_default_position
    # Defaults to the next highest position
    self.position = (Section.maximum(:position) || 0) + 1
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_many :resource_categories, dependent: :destroy
  has_many :categories, through: :resource_categories
  has_one_attached :preview
  has_one_attached :file_upload
  before_save :purge_old_file, if: :file_upload_changed?

  accepts_nested_attributes_for :resource_categories, allow_destroy: true

  private

  def purge_old_file
    file_upload.purge_later if file_upload.attached?
  end
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord

  validates :body, presence: false
  validates :name, presence: true
  validates :background_colour, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @menu_sections = Section.uncached do
        Section.where(hide_menu: false).order(Arel.sql('COALESCE(position, 999999), id'))
      end
      Rails.logger.debug "Menu Sections: #{@menu_sections.map { |s| { id: s.id, position: s.position } }}"
      @blogs = Blog.all
      @resources = Resource.all
      @sections = Section.all
      @users = User.all
      @reviews = Review.all
      @categories = Category.all
      @policies = Policy.all
      @coaching = Coaching.all
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/admin/dashboard/index.html.erb
<% content_for :meta_title, "Admin" %>
<% content_for :meta_description, "Admin Coaching" %>

<div class="container mx-auto p-6 max-w-7xl">
  <h1 class="text-xl font-bold mb-6 font-poppins">Admin Dashboard</h1>

<div class="flex mb-5 gap-6">
  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">

	<h2 class="text-lg font-semibold mb-4">Courses</h2>

	<div class="text-4xl text-center">
	  <%= @coaching.count %>
	</div>
  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Articles</h2>

	<div class="text-4xl text-center">
		<%= @blogs.count %>
	</div>
  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Reviews</h2>

	<div class="text-4xl text-center">
		<%= @reviews.count %>
	</div>
  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Resources</h2>

	<div class="text-4xl text-center">
		<%= @resources.count  %>
	</div>

  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Policies</h2>

	<div class="text-4xl text-center">
	  <%= @policies.count %>
	</div>
  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Categories</h2>

	<div class="text-4xl text-center">
	  <%= @categories.count %>
	</div>
  </div>

</div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md w-50">
	<h2 class="px-6 text-lg font-semibold mb-2 font-poppins">Sections</h2>
	<%= render partial: 'admin/dashboard/partials/sections', locals: { sections: @sections } %>

	<h2 class="px-6 text-lg font-semibold mb-2 font-poppins">Menu Builder</h2>
	<%= render partial: 'admin/dashboard/partials/menu_builder', locals: { sections: @home_sections } %>

	<h2 class="px-6 text-lg font-semibold mb-2 font-poppins">Coaching</h2>
	<%= render partial: 'admin/dashboard/partials/coaching', locals: { coaching: @coaching } %>

	<h2 class="px-6 text-lg font-semibold mb-2 font-poppins">Categories</h2>
	<%= render partial: 'admin/dashboard/partials/categories', locals: { category: @categories } %>

	<h2 class="px-6 text-lg font-semibold mb-2 font-poppins">Policies</h2>
	<%= render partial: 'admin/dashboard/partials/policies', locals: { policy: @policies } %>

  </div>
</div>

app/views/admin/dashboard/partials/_categories.html.erb
<div class="p-6 max-w-7xl mx-auto bg-gray-100 rounded-md space-y-2">

  <table class="table-fixed min-w-full divide-y divide-gray-300 border border-gray-300 mb-6">
	<thead class="bg-gray-50 w-full">
	<tr>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/6">Name</th>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-4/6">Area</th>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/6 text-center">Actions</th>
	</tr>
	</thead>
	<tbody class="bg-white divide-y divide-gray-200 w-full" id="categories">
	<% @categories.each do |category| %>
	<tr>
		<td class="px-6 w-1/6 table-cell whitespace-nowrap"><%= category.name %></td>
	  	<td class="px-6 w-4/6 whitespace-nowrap"><%= category.area %></td>
	  	<td class="px-8 py-4 w-1/6 whitespace-nowrap text-sm font-medium text-center">
	  		<%= link_to "Edit", edit_category_path(category), class: "p-3 bg-scb-blue text-white py-2 px-4 rounded mr-2" %>
	  		<%= link_to "Delete", category, method: :delete, class: "p-3 bg-red-700 text-white py-2 px-4 rounded" %>
		</td>
	</tr>
	<% end %>
	</tbody>
  </table>
  <%= link_to "Add new category", new_category_path, class: "bg-scb-blue text-white py-2 px-4 rounded" %>
</div>

app/views/admin/dashboard/partials/_coaching.html.erb
<div class="p-6 max-w-7xl mx-auto bg-gray-100 p-4 rounded-md space-y-2">

  <table class="min-w-full divide-y divide-gray-300 border border-gray-300 mb-6">
	<thead class="bg-gray-50 w-full">
	<tr>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/3">Title</th>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Content</th>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider text-center">Actions</th>
	</tr>
	</thead>
	<tbody class="bg-white divide-y divide-gray-200 w-full" id="categories">
	<% @coaching.each do |coach| %>
	  <tr>
		<td class="px-6"><%= coach.title %></td>
		<td class="px-6"><%= coach.description.truncate(80) %></td>
		<td class="px-8 py-4 whitespace-nowrap text-sm font-medium text-center">
		  <%= link_to "Edit", edit_coaching_path(coach), class: "p-3 bg-scb-blue text-white py-2 px-4 rounded mr-2" %>
		  <%= link_to "Delete", coaching_path(coach), method: :delete, class: "p-3 bg-red-700 text-white py-2 px-4 rounded" %>
		</td>
	  </tr>
	<% end %>
	</tbody>
  </table>
  <%= link_to "Add new course", new_coaching_path, class: "bg-scb-blue text-white py-2 px-4 rounded" %>
</div>

app/views/admin/dashboard/partials/_menu_builder.html.erb
<div>
  <ul class="flex flex-col bg-gray-100 p-4 rounded-md space-y-2" data-menu-builder-target="list" data-controller="menu-builder">
    
    <% @menu_sections.each do |section| %>
      <%= content_tag :li, data: {id: section.id}, class:"flex items-center gap-3 p-2 bg-white border border-gray-300 rounded-md cursor-pointer" do %>
        <span class="drag-handle cursor-grab text-gray-500 hover:text-gray-800">||</span>
        <a href="<%= root_path %>#<%= section.name.downcase %>" class="block text-gray-800 font-medium">
          <%= section.name %>
        </a>
      <% end %> 
    <% end %>

  </ul>  
</div>

app/views/admin/dashboard/partials/_policies.html.erb
<div class="p-6 max-w-7xl mx-auto bg-gray-100 p-4 rounded-md space-y-2">

  <table class="min-w-full divide-y divide-gray-300 border border-gray-300 mb-6">
	<thead class="bg-gray-50 w-full">
	<tr>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/3">Title</th>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Content</th>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider text-center">Actions</th>
	</tr>
	</thead>
	<tbody class="bg-white divide-y divide-gray-200 w-full" id="categories">
	<% @policies.each do |policy| %>
	  <tr>
		<td class="px-6"><%= policy.title %></td>
		<td><%= policy.content.truncate(80) %></td>
		<td class="px-8 py-4 whitespace-nowrap text-sm font-medium text-center">
		  <%= link_to "Edit", edit_policy_path(policy), class: "p-3 bg-scb-blue text-white py-2 px-4 rounded mr-2" %>
		  <%= link_to "Delete", policy, method: :delete, class: "p-3 bg-red-700 text-white py-2 px-4 rounded" %>
		</td>
	  </tr>
	<% end %>
	</tbody>
  </table>
  <%= link_to "Add new policy", new_policy_path, class: "bg-scb-blue text-white py-2 px-4 rounded" %>
</div>

app/views/admin/dashboard/partials/_sections.html.erb
<div class="p-6 max-w-7xl mx-auto bg-gray-100 rounded-md space-y-2">

  <table class="table-fixed min-w-full divide-y divide-gray-300 border border-gray-300 mb-6">
	<thead class="bg-gray-50 w-full">
	<tr>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/6">Name</th>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-4/6">Title</th>
	  <th class="px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider w-1/6 text-center">Actions</th>
	</tr>
	</thead>
	<tbody class="bg-white divide-y divide-gray-200 w-full" id="categories">
	<% @sections.each do |section| %>
	<tr>
		<td class="px-6 w-1/6 table-cell whitespace-nowrap"><%= section.name %></td>
	  	<td class="px-6 w-4/6 whitespace-nowrap"><%= section.title.truncate(30) %></td>
	  	<td class="px-8 py-4 w-1/6 whitespace-nowrap text-sm font-medium text-center">
	  		<%= link_to "Edit", edit_section_path(section), class: "p-3 bg-scb-blue text-white py-2 px-4 rounded mr-2" %>
	  		<%= link_to "Delete", section, method: :delete, class: "p-3 bg-red-700 text-white py-2 px-4 rounded" %>
		</td>
	</tr>
	<% end %>
	</tbody>
  </table>
  <%= link_to "Add new section", new_section_path, class: "bg-scb-blue text-white py-2 px-4 rounded" %>
</div>