config/routes.rb
Rails.application.routes.draw do
  get 'uploader/image'
  devise_for :users
  resources :sections
  resources :reviews
  resources :contacts
  resources :categories
  resources :policies
  resources :coachings, path: 'coaching'
  root 'home#index'

  namespace :admin do
    root to: 'dashboard#index'

    resources :blogs
    resources :resources
    resources :sections
    resources :users
    resources :reviews
    resources :categories
    resources :policies
    resources :coaching
  end

  resources :reorder do
    patch :move
  end

  post 'reorder/update_sections_order', to: 'reorder#update_sections_order'

  post 'uploader/image' => 'uploader#image'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'errors/not_found'
  get 'errors/internal_server_error'

  get '/contact_us', to: 'contact_us#new'
  post '/contact_us', to: 'contact_us#create'
  get 'contact_us/sent'
  get 'contact_us/error'

  resources :blogs, path: :blog

  resources :resources

  require 'active_storage/engine'
  ActiveStorage::Engine.routes.draw do
    get '/rails/active_storage/blobs/redirect/:signed_id/*filename' => 'active_storage/blobs#show',
        as: :rails_service_blob
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # test for deployment

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :blog_categories, dependent: :destroy
  has_many :categories, through: :blog_categories
  has_one_attached :preview

  accepts_nested_attributes_for :blog_categories, allow_destroy: true
end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/blogs_category.rb
class BlogsCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blog_categories
  has_many :blogs, through: :blog_categories
  validates :name, uniqueness: true
end

app/models/coaching.rb
class Coaching < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/contact_us.rb
# frozen_string_literal: true
class ContactUs < MailForm::Base
  attribute :name
  attribute :nickname
  attribute :subject
  attribute :email
  attribute :email_confirmation
  attribute :message

  validates :name, :subject,
            presence: true,
            allow_blank: false,
            format: { with: /\A[a-zA-Z\s-]+\z/, message: 'Only allows letters, spaces, and hyphens' }

  validates :email,
            presence: true, format: { with: URI::MailTo::EMAIL_REGEXP },
            allow_blank: false,
            length: {
              minimum: 5,
              maximum: 50
            }

  validates :email_confirmation,
            presence: true

  validate :emails_match

  validates :message,
            allow_blank: false,
            length: {
              minimum: 10,
              maximum: 500
            }

  def headers
    {
      to: 'stuart@scbexecutivecoaching.com', # change this to be the email you want sent to
      subject: 'SCB Executive Coaching Query',
      from: 'stuart@scbexecutivecoaching.com',  # change this to be the email it is coming from
      reply_to: %("#{name}" <#{email}>)
    }
  end

  def emails_match
    if email != email_confirmation
      errors.add(:email_confirmation, "doesn't match Email")
    end
  end
end

app/models/policy.rb
class Policy < ApplicationRecord
end

app/models/reorder.rb
class Reorder < ApplicationRecord
  validates :position, presence: true
  validates :position, numericality: { only_integer: true, greater_than: 0 }
  #has_many :sections, -> { order(position: :asc) }, dependent: :destroy

  private
  def set_default_position
    # Defaults to the next highest position
    self.position = (Section.maximum(:position) || 0) + 1
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_many :resource_categories, dependent: :destroy
  has_many :categories, through: :resource_categories
  has_one_attached :preview
  has_one_attached :file_upload
  before_save :purge_old_file, if: :file_upload_changed?

  accepts_nested_attributes_for :resource_categories, allow_destroy: true

  private

  def purge_old_file
    file_upload.purge_later if file_upload.attached?
  end
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord

  validates :body, presence: false
  validates :name, presence: true
  validates :background_colour, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/admin/index.html.erb
<% content_for :meta_title, "Admin" %>
<% content_for :meta_description, "Admin Coaching" %>

<div class="container mx-auto p-6 max-w-7xl">
  <h1 class="text-xl font-bold mb-6 font-poppins">Admin Dashboard</h1>

<div class="flex mb-5 gap-6">
  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">

	<h2 class="text-lg font-semibold mb-4">Courses</h2>

	<div class="text-4xl text-center">
	  <%= @coaching.count %>
	</div>
  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Articles</h2>

	<div class="text-4xl text-center">
		<%= @blogs.count %>
	</div>
  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Reviews</h2>

	<div class="text-4xl text-center">
		<%= @reviews.count %>
	</div>
  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Resources</h2>

	<div class="text-4xl text-center">
		<%= @resources.count  %>
	</div>

  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Policies</h2>

	<div class="text-4xl text-center">
	  <%= @policies.count %>
	</div>
  </div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md">
	<h2 class="text-lg font-semibold mb-4">Categories</h2>

	<div class="text-4xl text-center">
	  <%= @categories.count %>
	</div>
  </div>

</div>

  <div class="menu-builder-section bg-gray-100 p-6 rounded-md shadow-md w-50">
	<h2 class="px-6 text-lg font-semibold mb-2 font-poppins">Menu Builder</h2>
	<%= render partial: 'admin/partials/menu_builder', locals: { sections: @home_sections } %>

	<h2 class="px-6 text-lg font-semibold mb-2 font-poppins">Coaching</h2>
	<%= render partial: 'admin/partials/coaching', locals: { coaching: @coaching } %>

	<h2 class="px-6 text-lg font-semibold mb-2 font-poppins">Categories</h2>
	<%= render partial: 'admin/partials/categories', locals: { category: @categories } %>

	<h2 class="px-6 text-lg font-semibold mb-2 font-poppins">Policies</h2>
	<%= render partial: 'admin/partials/policies', locals: { policy: @policies } %>

  </div>
</div>

app/views/resources/_form.html.erb
<%= form_with(model: resource, class: "contents", multipart: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :author %>
    <%= form.text_field :author, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :preview %>
    <%= form.file_field :preview, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    <p class="text-sm">This is a preview image. This will be used on Blog landing page.</p>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    <p class="text-sm">Add a brief description of the article. This will be used for SEO and on Blog landing page. Minimum 240 characters.</p>
  </div>

  <div data-controller="tinymce">
    <div class="my-5">
      <%= form.label :body %>
      <%= form.text_area :body, :class => "tinymce block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full", id: "section_body",  data: { tinymce_target: "textarea" } %>
    </div>
  </div>

  <div class="my-5">
    <%= form.label :file_upload %>
    <%= form.file_field :file_upload, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    <p class="text-sm">This is a file upload field. Use this for image or pdf uploads etc..</p>
  </div>

  <div class="my-5">
    <%= form.label :link %>
    <%= form.text_field :link, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="field mb-5">
    <%= form.label :category_id, "Category" %>
    <%= form.collection_select :category_id, resource_categories, :id, :name, prompt: 'Select a Category' %>
    <%= link_to "Add Category", new_category_path, class: "rounded-lg py-3 px-5 bg-scb-green text-white inline-block font-medium cursor-pointer ml-3" %>
    <p class="text-sm text-gray-500">Please submit the blog before clicking on the add category button.</p>
  </div>



  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-scb-blue  text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div  id="<%= dom_id resource %>" class="max-w-sm bg-white border border-gray-200 rounded-lg shadow">
  <a href="#">
    <% if resource.preview.present? %>
      <img class="rounded-t-lg min-h-382 max-h-382 min-w-full max-w-382" src="<%= url_for(resource.preview) %>" alt="<%= resource.title %>" />
    <% end %>
  </a>
  <div class="p-5">
    <%= link_to  resource do %>
      <div class="flex justify-between items-center">
      <h5 class="text-2xl font-bold tracking-tight text-gray-900 dark:text-scb-black"><%= resource.title %></h5>
      <div class="flex gap-1 items-center">
        <% if resource.resource_categories.any? %>
          <% resource.categories.each do |category| %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 0 0 3 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 0 0 5.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 0 0 9.568 3Z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6Z" />
        </svg>
        <span class="leading-none"><%=category.name %></span>
          <% end %>
        <% end %>
      </div>
      </div>
    <% end %>

    <hr class="h-px my-4 bg-gray-200 border-0 dark:bg-gray-700">

    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400 min-h-132 max-h-132 h-full"><%= resource.description.truncate(236) %></p>

    <% if resource.link.present? %>
      <%= link_to resource.link, class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-scb-green rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-blue-300" do %>
        <span>Read more</span>
        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
        </svg>
       <% end %>
    <% else %>
      <% if resource.file_upload.present? %>
      <%= link_to rails_blob_url(resource.file_upload, disposition: "attachment"), class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-scb-blue rounded-lg hover:bg-blue-200 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-scb-blue dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
        <span>Download</span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 ml-2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 16v-8m0 8l-3.5-3.5m3.5 3.5l3.5-3.5M9.5 12m5 0L9.5 8.5m5 3.5L9.5 15.5m10.5 2.5a4.5 4.5 0 000-9 4.5 4.5 0 00-4.5 4.5m5 0h-5" />
        </svg>
      <% end %>
      <% else %>
      <p>No file uploaded</p>
    <% end %>
    <% end %>

    <% if user_signed_in? %>
    <%= link_to "View", resource_path(resource.id) %>
      <% end %>

  </div>
</div>

app/views/resources/edit.html.erb
<div class="p-6 mx-auto md:w-2/3 max-w-7xl">
  <h1 class="font-bold text-4xl mt-3">Edit Resource</h1>

  <%= render "form", resource: @resource, resource_categories: @resource_categories %>

  <%#= link_to "Read this Article", @blog, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to Resources", resource_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/resources/index.html.erb
<% content_for :meta_title, "Resources" %>
<% content_for :meta_description, 'Downloads and links from SCB Executive Coaching' %>

<div class="w-full bg-scb-white p-6">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Resources" %>

  <div class="p-6 max-w-7xl mx-auto flex flex-col items-center">
    <div class="flex items-center justify-between w-full">
      <h1 class="font-bold text-4xl">Resources</h1>
      <%= link_to "New resource", new_resource_path, class: "rounded-lg py-3 px-5 bg-scb-blue text-white block font-medium" %>
    </div>
  </div>

  <div id="resources" class="max-w-7xl mx-auto  p-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <% @resources.each do |resource| %>
      <%= render resource %>
    <% end %>
  </div>
</div>

app/views/resources/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Resource</h1>

  <%= render partial: "form", locals: { resource: @resource, resource_categories: @resource_categories } %>

  <%= link_to "Back to resources", resources_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/resources/show.html.erb
<% if @resource.present? %>
  <% content_for :meta_title, "#{@resource.title}" %>
  <% content_for :meta_description, @resource.description %>

  <% if @resource.preview.present? %>
  	<% content_for :meta_image, "#{url_for(@resource.preview)}" %>
  <% end %>

  <div class="mx-auto max-w-7xl p-6 bg-scb-white text-left">
	<% if notice.present? %>
	  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
	<% end %>

	<% if @resource.preview.present? %>
		<img src="<%= url_for(@resource.preview) %>" alt="<%= @resource.title %>" class="w-full h-96 object-cover rounded-lg">
	<% end %>

	<div class="mt-6">
	  <h1 class="text-4xl mb-3"><%= @resource.title %></h1>
	  <hr class="h-px my-4 bg-gray-200 border-0 dark:bg-gray-700">

	  <div id="titleBar" class="flex gap-3">
		<div class="flex gap-1 items-center">
		  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
			<path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
		  </svg>
		  <span class="leading-none mt-1"><%= @resource.created_at.strftime("%B %d, %Y") %></span>
		</div>

		<div class="flex gap-1 items-center">
		  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
			<path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
		  </svg>
		  <span class="leading-none mt-1"><%= @resource.author %></span>
		</div>

		<% if @resource.resource_categories.any? %>
		  <% @resource.categories.each do |category| %>
		  <div class="flex gap-1 items-center">
			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
			  <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 0 0 3 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 0 0 5.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 0 0 9.568 3Z" />
			  <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6Z" />
			</svg>
			<span class="leading-none mt-1"><%= category.name %></span>
		  </div>
		<% end %>
		  <% end %>
	  </div>

	  <hr class="h-px my-4 bg-gray-200 border-0 dark:bg-gray-700">
	  <h2><%= @resource.body&.html_safe %></h2>
	</div>

	<hr class="h-px my-4 bg-gray-200 border-0 dark:bg-gray-700">

	<%= link_to "Edit this resource", edit_resource_path(@resource), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
	<%= link_to "Back to resource", resources_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
	<div class="inline-block ml-2">
	  <%= button_to "Destroy this resource", @resource, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium bg-red-700 text-scb-white" %>
	</div>
  </div>
<% else %>
  <p>Resource not found.</p>
<% end %>

app/views/shared/_contact.html.erb
<section id="contact" class="bg-scb-black text-scb-white relative">
  <div class="container mx-auto max-w-7xl py-16">

    <div id="socials" class="w-2/3 mx-auto text-center">
      <h3 class="text-3xl font-poppins font-bold mb-5">Our social channels</h3>

      <div id="socialcons" class="flex flex-row justify-center">

        <!-- linkedin -->
        <a href="https://rwmbxa.clicks.mlsend.com/tl/cl/eyJ2Ijoie1wiYVwiOjEwMjM2NDAsXCJsXCI6MTQxNzk4NjI2MDQzMTAyNDAxLFwiclwiOjE0MTkwMjg4MDUxMTYyNDk2NH0iLCJzIjoiMTZhMzcyMGMyMGI5MTljNSJ9" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48px" height="48px">
            <rect width="48" height="48" fill="#111111" />
            <path fill="white" d="M14.5 19h5v15h-5zM24 19h4.8v2.2h.1c.7-1.3 2.4-2.8 4.9-2.8 5.1 0 6.1 3.3 6.1 7.5V34h-5v-7.4c0-1.8-.5-3.6-2.6-3.6s-3 1.9-3 3.8V34h-5zM17 14c0 1.4-1.1 2.5-2.5 2.5S12 15.4 12 14s1.1-2.5 2.5-2.5S17 12.6 17 14z"/>
          </svg>
        </a>

        <!-- youtube -->
        <a href="https://rwmbxa.clicks.mlsend.com/tl/cl/eyJ2Ijoie1wiYVwiOjEwMjM2NDAsXCJsXCI6MTQxNzk4NjI2MDQ2MjQ4MTMwLFwiclwiOjE0MTkwMjg4MDUxMTYyNDk2NH0iLCJzIjoiNDNkNDY2NmYyNGIwNDA1OCJ9" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48px" height="48px">
            <rect width="48" height="48" fill="#111111" />
            <path fill="white" d="M34.5 15.5c-.3-1.1-1.2-2-2.4-2.3C29.5 12.5 24 12.5 24 12.5s-5.5 0-8.1.7c-1.2.3-2.1 1.2-2.4 2.3-.7 2.6-.7 8-.7 8s0 5.4.7 8c.3 1.1 1.2 2 2.4 2.3C18.5 35.5 24 35.5 24 35.5s5.5 0 8.1-.7c1.2-.3 2.1-1.2 2.4-2.3.7-2.6.7-8 .7-8s0-5.4-.7-8zM20.5 27V19l8 4-8 4z"/>
          </svg>
        </a>


        <!-- facebook -->
        <a href="https://rwmbxa.clicks.mlsend.com/tl/cl/eyJ2Ijoie1wiYVwiOjEwMjM2NDAsXCJsXCI6MTQxNzk4NjI2MDUwNDQyNDM1LFwiclwiOjE0MTkwMjg4MDUxMTYyNDk2NH0iLCJzIjoiM2Q5NmYzOGE2YjEyY2RlMyJ9" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48px" height="48px">
            <rect width="48" height="48" fill="#111111" />
            <path fill="white" d="M29 15h-4c-1.1 0-2 .9-2 2v3h6v4h-6v10h-5V24h-4v-4h4v-3c0-3.3 2.7-6 6-6h4v4z"/>
          </svg>
        </a>

      </div>
    </div>

    <div class="flex flex-row justify-between text-center py-16">

      <div>
        <h3 class="text-3xl font-poppins font-bold mb-5">Contact Us</h3>
        <p class="mb-5">Contact our team for questions or information</p>

        <a href="#intros" class="absolute right-2 bottom-2"><button class="bg-scb-gray text-scb-black rounded-full  p-3">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 10.5 12 3m0 0 7.5 7.5M12 3v18" />
          </svg>
        </button>
        </a>

        <a href="mailto:stuart@scbexecutivecoaching.com" class="mb-5">stuart@scbexecutivecoaching.com</a>

        <p class="mb-5">07724 353503</p>

        <p>
          <span class="block">SCB Executive Coaching Ltd</span>
          <span class="block m-3">63 Green Lane, Windsor, SL4 3QD</span>
          <span class="block">Registered in England and Wales</span>
          <span class="block">Company Number: 14872740</span>
        </p>
      </div>

      <%= render partial: 'shared/mailerlite' %>
    </div>

    <ul class="flex gap-2 flex-row justify-center mb-3">
      <% Policy.all.each do |policy| %>
        <li><%= link_to policy.title, policy_path(policy) %></li>
      <% end %>
    </ul>

    <p class="text-center">Copyright <%= Time.current.year %> SCB Executive Coaching Ltd. All rights reserved.</p>
  </div>
</section>

app/views/shared/_menu.html.erb
<div class="space-y-1 py-6">
  <% @menu_sections.order(:position).each do |section| %>
	<!-- If the item is a homepage section -->
	<% if section.show_on_home %>
	  <a href="<%= "#{root_path}##{section.name.downcase}" %>"
		 class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-scb-white hover:bg-gray-950">
		<%= section.name %>
	  </a>
	<% elsif section.custom_link.present? %>
	  <!-- If the item is a standalone page with a custom link -->
	  <a href="<%= section.custom_link %>"
		 class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-scb-white hover:bg-gray-950">
		<%= section.name %>
	  </a>
	<% end %>
  <% end %>
</div>

app/views/shared/_mobile-menu.html.erb
<div class="hidden lg:flex lg:gap-x-12">
  <% if @menu_sections.present? %>
	<% @menu_sections.order(:position).each do |section| %>
	  <% unless section.hide_menu %>
		<!-- If the item is a homepage section -->
		<% if section.show_on_home %>
		  <a href="<%= "#{root_path}##{section.name.downcase}" %>"
			 class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-scb-white hover:bg-gray-950">
			<%= section.name %>
		  </a>
		<% else %>
		  <!-- If the item is a standalone page -->
		  <a href="<%= eval(section.custom_link) %>"
			 class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-scb-white hover:bg-gray-950">
			<%= section.name %>
		  </a>
		<% end %>
	  <% end %>
	<% end %>
  <% end %>
</div>