config/routes.rb
Rails.application.routes.draw do
  get 'uploader/image'
  devise_for :users
  resources :sections
  resources :reviews
  resources :contacts
  resources :categories
  resources :policies
  resources :coachings, path: 'coaching'
  root 'home#index'

  namespace :admin do
    root to: 'dashboard#index'

    resources :blogs
    resources :resources
    resources :sections
    resources :users
    resources :reviews
    resources :categories
    resources :policies
    resources :coaching
  end

  resources :reorder do
    patch :move
  end

  post 'reorder/update_sections_order', to: 'reorder#update_sections_order'

  post 'uploader/image' => 'uploader#image'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'errors/not_found'
  get 'errors/internal_server_error'

  get '/contact_us', to: 'contact_us#new'
  post '/contact_us', to: 'contact_us#create'
  get 'contact_us/sent'
  get 'contact_us/error'

  resources :blogs, path: :blog

  resources :resources

  require 'active_storage/engine'
  ActiveStorage::Engine.routes.draw do
    get '/rails/active_storage/blobs/redirect/:signed_id/*filename' => 'active_storage/blobs#show',
        as: :rails_service_blob
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # test for deployment

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :blog_categories, dependent: :destroy
  has_many :categories, through: :blog_categories
  has_one_attached :preview

  accepts_nested_attributes_for :blog_categories, allow_destroy: true
end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/blogs_category.rb
class BlogsCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blog_categories
  has_many :blogs, through: :blog_categories
  validates :name, uniqueness: true
end

app/models/coaching.rb
class Coaching < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/contact_us.rb
# frozen_string_literal: true
class ContactUs < MailForm::Base
  attribute :name
  attribute :nickname
  attribute :subject
  attribute :email
  attribute :email_confirmation
  attribute :message

  validates :name, :subject,
            presence: true,
            allow_blank: false,
            format: { with: /\A[a-zA-Z\s-]+\z/, message: 'Only allows letters, spaces, and hyphens' }

  validates :email,
            presence: true, format: { with: URI::MailTo::EMAIL_REGEXP },
            allow_blank: false,
            length: {
              minimum: 5,
              maximum: 50
            }

  validates :email_confirmation,
            presence: true

  validate :emails_match

  validates :message,
            allow_blank: false,
            length: {
              minimum: 10,
              maximum: 500
            }

  def headers
    {
      to: 'stuart@scbexecutivecoaching.com', # change this to be the email you want sent to
      subject: 'SCB Executive Coaching Query',
      from: 'stuart@scbexecutivecoaching.com',  # change this to be the email it is coming from
      reply_to: %("#{name}" <#{email}>)
    }
  end

  def emails_match
    if email != email_confirmation
      errors.add(:email_confirmation, "doesn't match Email")
    end
  end
end

app/models/policy.rb
class Policy < ApplicationRecord
end

app/models/reorder.rb
class Reorder < ApplicationRecord
  validates :position, presence: true
  validates :position, numericality: { only_integer: true, greater_than: 0 }
  #has_many :sections, -> { order(position: :asc) }, dependent: :destroy

  private
  def set_default_position
    # Defaults to the next highest position
    self.position = (Section.maximum(:position) || 0) + 1
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_many :resource_categories, dependent: :destroy
  has_many :categories, through: :resource_categories
  has_one_attached :preview
  has_one_attached :file_upload
  before_save :purge_old_file, if: :file_upload_changed?

  accepts_nested_attributes_for :resource_categories, allow_destroy: true

  private

  def purge_old_file
    file_upload.purge_later if file_upload.attached?
  end
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord

  validates :body, presence: false
  validates :name, presence: true
  validates :background_colour, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Category created successfully"
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render json: @category, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :area)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/views/categories/_category.html.erb
<tr id="<%= dom_id(category) %>">
  <td class="px-8 py-4 whitespace-nowrap text-md font-medium text-gray-900"><%= category.name %></td>
  <td class="px-8 py-4 whitespace-nowrap text-md font-medium text-gray-900"><%= category.area %></td>
  <td class="px-8 py-4 whitespace-nowrap text-sm font-medium">
	<%= link_to "Edit", edit_category_path(category), class: "p-3 bg-scb-blue text-white py-2 px-4 rounded mr-2" %>
	<%= link_to "Delete", category, method: :delete, class: "p-3 bg-red-700 text-white py-2 px-4 rounded" %>
  </td>
</tr>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true, data: { turbo_frame: "category_form" }) do |form| %>
  <% if category.errors.any? %>
	<div class="error_messages">
	  <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
	  <ul>
		<% category.errors.full_messages.each do |message| %>
		  <li><%= message %></li>
		<% end %>
	  </ul>
	</div>
  <% end %>

  <div class="field">
	<%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
	<%= form.text_field :name, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
  </div>

  <div class="field">
	<%= form.label :area %>
	<%= form.select :area, options_for_select([['Blog', 'blog'], ['Resource', 'resource']], category.area) %>
  </div>

  <div class="mt-3 mb-3">
	<%= form.submit class: "rounded-lg py-3 px-5 bg-scb-blue  text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="p-6 mx-auto md:w-2/3 max-w-7xl">
  <h1 class="font-bold text-4xl mt-3">Edit Category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to Articles", blog_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to Categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="p-6 max-w-7xl mx-auto">
  <h1 class="text-4xl mb-6">Categories</h1>

  <table class="min-w-full divide-y divide-gray-300 border border-gray-300 mb-6">
	<thead class="bg-gray-50">
	<tr>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Area</th>
	  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
	</tr>
	</thead>
	<tbody class="bg-white divide-y divide-gray-200" id="categories">
	<% @categories.each do |category| %>
	  <%= render category %>
	<% end %>
	</tbody>
  </table>
  <%= link_to "Add new category", new_category_path, class: "bg-scb-blue text-white py-2 px-4 rounded" %>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Category</h1>

  <%= render "form", category: @category %>

  <div class="flex gap-3">
  	<%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  	<%= link_to "Back to articles", blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>